// <auto-generated />
namespace PMY.CompilationSystem.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _181226change2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_181226change2));
        
        string IMigrationMetadata.Id
        {
            get { return "201812261022105_181226change2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
